apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: external-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - external-pool
  peers:
  - rack1-001-leaf1
  - rack1-001-leaf2
  - rack2-001-leaf1
  - rack2-001-leaf2
  aggregationLength: 32         # Advertise /32 routes, not blocks
