apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: external-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - external-pool
  peers:
  - to-rack1-leaf1
  - to-rack1-leaf2
  - to-rack2-leaf1
  - to-rack2-leaf2
  aggregationLength: 32         # Advertise /32 routes, not blocks
